#
ENVIRONMENT: staging

# gcp
GOOGLE_API_KEY: AIzaSyAdQ-zq9XwoTRtzToYo6A5t7afxUJ39CTc

LLAMA_CLOUD_API_KEY: llx-qpB1eyxEtf7TXIvEaPWcpG5Fu6xfaXDCoiFJ62EZ6UUFrLhE

WIKIRATE_API_KEY: JoDaOQXoU2vzgRAbaArQlwtt
